eureka:
  client:
    serviceUrl:
      defaultZone: http://registry/eureka/

spring:
  datasource:
    url: jdbc:postgresql://database:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    platform: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


server:
  context-path: /ordering